@baseUrl = http://127.0.0.1:8000/api
@token = 1|X0LQMMlzvCskxDhXH7PJdfJhUkcH0OeMhdUmjV0h344b59b5

### Login admin
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Login waiter
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "tesztelek@waiter.com",
    "password": "password123"
}

### Me
GET {{baseUrl}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Get all table
GET {{baseUrl}}/tables
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Get all waiter
GET {{baseUrl}}/admin/waiters
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{}

### Add waiter
POST {{baseUrl}}/admin/waiters
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek@waiter.com",
    "password": "password123",
    "password_confirmation": "password123"
}

### Delete waiter
DELETE {{baseUrl}}/admin/waiters/3
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{}


### Make reservation
POST {{baseUrl}}/reservations
Content-Type: application/json
Accept: application/json

{
  "guest_name": "Horvath Anna",
  "phone_number": "+36708566559",
  "guest_count": 2,
  "start_time": "2026-02-24T9:28:20Z"
}

### Waiter to table
POST {{baseUrl}}/tables/7/orders
Authorization: Bearer {{token}}
Content-Type: application/json
