@baseUrl = http://127.0.0.1:8000/api
@token = 12|zZtRLZG7nZkvg5qzCYpkwTlCIK0XGLK47YLPnv6u5188b2fc

### Login admin
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Login waiter
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "tesztelek@waiter.com",
    "password": "password123"
}

### Me
GET {{baseUrl}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Get all table
GET {{baseUrl}}/tables
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Add waiter
POST {{baseUrl}}/add-waiter
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek@waiter.com",
    "password": "password123",
    "password_confirmation": "password123"
}

### Delete waiter
DELETE {{baseUrl}}/delete-waiter
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "email": "seeder@waiter.com"
}
