@baseUrl = http://127.0.0.1:8000/api
@token = 2|prLSIwPzPczFJZt9P0Pb7wSDyMP5Hh2x8QD9r9fVb08068f0

### Login admin
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Login waiter
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "seeder@waiter.com",
    "password": "password123"
}

### Me
GET {{baseUrl}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Get all table
GET {{baseUrl}}/tables
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{}

### Get all waiter
GET {{baseUrl}}/admin/waiters
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{}

### Add waiter
POST {{baseUrl}}/admin/waiters
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek@waiter.com",
    "password": "password123",
    "password_confirmation": "password123"
}

### Delete waiter
DELETE {{baseUrl}}/admin/waiters/3
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{}


### Make reservation
POST {{baseUrl}}/reservations
Content-Type: application/json
Accept: application/json

{
  "guest_name": "Kalocs Pista",
  "phone_number": "+36706566559",
  "guest_count": 6,
  "start_time": "2026-02-24T18:4:00Z"
}

### Waiter to table
POST {{baseUrl}}/tables/10/orders
Authorization: Bearer {{token}}
Content-Type: application/json

### Add order item to an order
POST {{baseUrl}}/orders/1/items
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "menu_item_id": 4,
    "quantity": 2
}

### Ready to pay simulation
POST {{baseUrl}}/orders/1/simulate-ready
Authorization: Bearer {{token}}
